### PR TITLE
Issue 597  add the huber norm

### PR DESCRIPTION
**Pull request by aringh**
Part of #597. Implements Huber norm with gradient and proximal operator.

### CODE REVIEW

**Comment by mehrhardt** [comment]
It looks quite good to me. There is a current pull request #1194 in which I do the same (see misc.py). However, we both focus on different aspects of the Huber norm and it would be good to merge the two. I did not bother with gradient as I don't need it but therefore included the convex conjugate. Moreover, my version is slightly more general as it allows to operate on vector-valued functions. Again this is due to my application.

**Comment by kohr-h** [comment]
Merging in the Git sense doesn't make any sense here, so my suggestion is that one just cherry-picks the good parts from the other. Probably you would have less to pick @mehrhardt, so I'd assume it would be easier to merge that way. We'll then close the other PR and merge the merged one.

**Comment by adler-j** [comment]
I agree with @kohr-h, this should be cherry-picked to the other branch.

**Comment by mehrhardt** [comment]
I now combined this version of the Huber norm with my version in #1191.

**Comment by aringh** [comment]
Sounds good to me :-) I guess we close this?

**Comment by adler-j** [comment]
Closing this, terribly sorry about the double work for you @aringh

**Comment by kohr-h** [comment]
At least large parts of the documentation and the tests made it, plus the gradient, so it was still very useful.

**Comment by mehrhardt** [comment]
Oh, I recycled pretty much all of it. Our contributions complemented each other very well @aringh.

**Comment by aringh** [comment]
No worries. The important thing is make `odl` develop, and also hopefully learning a thing or two on the way ;-)

**Pull request closed without merging**
