### PR TITLE
ENH: Improve runtime of PointwiseNorm, closes #1314

### LINKED ISSUE #1314: algorithm is slowing down (again)
I am having a similar issue as in #1291 but it is also somewhat different. I do observe that after a certain number of iterations the algorithm is slowing down massively. I have tried many things to figure out what is going wrong but with no success. 
The smallest example where I observe this behaviour is the following. This "minimal example" has two problems. First, it does depend on the "spdhg" package which is not yet part of ODL. Second, it is not really small. However, I was not able to create a smaller example that shows the same behaviour. Also as you can see with my comments, changing the example slightly in almost whatever way resolves the problem ... Do you have any idea of what might go wrong here / what to look at?

```
import odl.contrib.solvers.spdhg as spdhg
import odl

niter_target = 100
#n = 10   # works perfect!
n = 100
X = odl.uniform_discr(min_pt=[-20, -20], max_pt=[20, 20], shape=[n, n])

geometry = odl.tomo.parallel_beam_geometry(X, num_angles=20, det_shape=20)
G = odl.tomo.RayTransform(X, geometry, impl='astra_cpu')
#G = odl.IdentityOperator(X) # works perfect!
#
Y = G.range
groundtruth = X.one()

#sinogram = 1 * Y.one() # works perfect!
sinogram = 100 * Y.one()
#factors = 1 * Y.one() # works perfect!
factors = 34 * Y.one()

background = 10 * Y.one()
data = factors * sinogram
#f = odl.solvers.L2NormSquared(Y).translated(-background) # works perfect!
f = odl.solvers.KullbackLeibler(Y, data).translated(-background)
A = factors * G

#g = odl.solvers.functional.ConstantFunctional(X, 0) # works perfect!
#g = odl.solvers.L1Norm(X) # works perfect!
g = spdhg.TotalVariationNonNegative(X, alpha=1e-1)
g.prox_options['p'] = None

callback = odl.solvers.CallbackPrintTiming(step=1, cumulative=False)

odl.solvers.pdhg(X.zero(), f, g, A, 1, 1, niter_target, callback=callback)
```

Output:
> Time elapsed = 0.036 s
> Time elapsed = 0.031 s
> Time elapsed = 0.031 s
> Time elapsed = 0.033 s
> Time elapsed = 0.031 s
> Time elapsed = 0.031 s
> Time elapsed = 0.034 s
> Time elapsed = 0.035 s
> Time elapsed = 0.031 s
> Time elapsed = 0.034 s
> Time elapsed = 0.031 s
> Time elapsed = 0.032 s
> Time elapsed = 0.037 s
> Time elapsed = 0.033 s
> Time elapsed = 0.034 s
> Time elapsed = 0.035 s
> Time elapsed = 0.035 s
> Time elapsed = 0.031 s
> Time elapsed = 0.035 s
> Time elapsed = 0.031 s
> Time elapsed = 0.031 s
> Time elapsed = 0.038 s
> Time elapsed = 0.034 s
> Time elapsed = 0.032 s
> Time elapsed = 0.034 s
> Time elapsed = 0.032 s
> Time elapsed = 0.031 s
> Time elapsed = 0.040 s
> Time elapsed = 0.038 s
> Time elapsed = 0.034 s
> Time elapsed = 0.038 s
> Time elapsed = 0.031 s
> Time elapsed = 0.031 s
> Time elapsed = 0.037 s
> Time elapsed = 0.034 s
> Time elapsed = 0.032 s
> Time elapsed = 0.035 s
> Time elapsed = 0.034 s
> Time elapsed = 0.032 s
> Time elapsed = 0.037 s
> Time elapsed = 0.042 s
> Time elapsed = 0.034 s
> Time elapsed = 0.039 s
> Time elapsed = 0.031 s
> Time elapsed = 0.034 s
> Time elapsed = 0.036 s
> Time elapsed = 0.031 s
> Time elapsed = 0.034 s
> Time elapsed = 0.039 s
> Time elapsed = 0.031 s
> Time elapsed = 0.034 s
> Time elapsed = 0.032 s
> Time elapsed = 0.035 s
> Time elapsed = 0.034 s
> Time elapsed = 0.130 s
> Time elapsed = 0.432 s
> Time elapsed = 0.536 s
> Time elapsed = 0.566 s
> Time elapsed = 0.575 s
> Time elapsed = 0.592 s
> Time elapsed = 0.586 s
> Time elapsed = 0.586 s
> Time elapsed = 0.588 s
> Time elapsed = 0.587 s
> Time elapsed = 0.587 s
> Time elapsed = 0.590 s
> Time elapsed = 0.592 s
> Time elapsed = 0.588 s
> Time elapsed = 0.592 s
> Time elapsed = 0.603 s
> Time elapsed = 0.606 s
> Time elapsed = 0.676 s
> Time elapsed = 0.597 s
> Time elapsed = 0.592 s
> Time elapsed = 0.595 s
> Time elapsed = 0.593 s
> Time elapsed = 0.602 s
> Time elapsed = 0.599 s
> Time elapsed = 0.601 s
> Time elapsed = 0.598 s
> Time elapsed = 0.600 s
> Time elapsed = 0.600 s
> Time elapsed = 0.596 s
> Time elapsed = 0.602 s
> Time elapsed = 0.608 s
> Time elapsed = 0.602 s
> Time elapsed = 0.602 s
> Time elapsed = 0.605 s
> Time elapsed = 0.598 s
> Time elapsed = 0.595 s
> Time elapsed = 0.594 s
> Time elapsed = 0.599 s
> Time elapsed = 0.596 s
> Time elapsed = 0.597 s
> Time elapsed = 0.599 s
> Time elapsed = 0.599 s
> Time elapsed = 0.600 s
> Time elapsed = 0.606 s
> Time elapsed = 0.607 s
> Time elapsed = 0.602 s

### PR DESCRIPTION
**Pull request by adler-j**
Can @mehrhardt check if this helps? The given code example does not work on master so it's hard for me to verify.

### CODE REVIEW

**Comment by mehrhardt** [comment]
I got the following error message:

```

  File "<ipython-input-1-856bf023b60f>", line 357, in <module>
    odl.solvers.pdhg(X.zero(), f, g, A, 1, 1, niter_target, callback=callback)

  File "/home/ehrhardt/repositories/github_myodl/odl/solvers/nonsmooth/primal_dual_hybrid_gradient.py", line 284, in pdhg
    proximal_primal_tau(primal_tmp, out=x)

  File "<ipython-input-1-856bf023b60f>", line 222, in tv_prox
    proj_P, tol=opts['tol'])

  File "<ipython-input-1-856bf023b60f>", line 298, in fgp_dual
    proj_P(pnew, out=pnew)

  File "<ipython-input-1-856bf023b60f>", line 203, in proj_P
    return norm.convex_conj.proximal(0)(x, out=out)

  File "/home/ehrhardt/repositories/github_myodl/odl/operator/operator.py", line 678, in __call__
    result = self._call_in_place(x, out=out, **kwargs)

  File "/home/ehrhardt/repositories/github_myodl/odl/solvers/nonsmooth/proximal_operators.py", line 1223, in _call
    denom = pwnorm(diff)

  File "/home/ehrhardt/repositories/github_myodl/odl/operator/operator.py", line 686, in __call__
    out = self._call_out_of_place(x, **kwargs)

  File "/home/ehrhardt/repositories/github_myodl/odl/operator/operator.py", line 50, in _default_call_out_of_place
    result = op._call_in_place(x, out, **kwargs)

  File "/home/ehrhardt/repositories/github_myodl/odl/operator/tensor_ops.py", line 232, in _call
    self._call_vecfield_p(f, out)

  File "/home/ehrhardt/repositories/github_myodl/odl/operator/tensor_ops.py", line 287, in _call_vecfield_p
    self._abs_pow_ufunc(out, out=out, p=(1 / self.exponent))

  File "/home/ehrhardt/repositories/github_myodl/odl/operator/tensor_ops.py", line 294, in _abs_pow_ufunc
    out.ufuncs.sqrt(p, out=out)

TypeError: wrapper() got multiple values for argument 'out'
```

**Comment by adler-j** [comment]
Any chance you could provide some code that allows me to reproduce this?

**Comment by mehrhardt** [comment]
This example produces the same error as described above.

```
import odl

n = 100
X = odl.uniform_discr(min_pt=[-20, -20], max_pt=[20, 20], shape=[n, n])
Y = X**2
f = odl.solvers.GroupL1Norm(Y)
A = odl.IdentityOperator(Y)
g = odl.solvers.ZeroFunctional(Y)
callback = odl.solvers.CallbackPrintTiming(step=1, cumulative=False)
odl.solvers.pdhg(Y.zero(), f, g, A, 1, 1, 100, callback=callback)
```

**Comment by mehrhardt** [comment]
Thanks @kohr-h for spotting this. It indeed resolves the problem. I think it is not worth me making the change and creating a PR. @adler-j could you make this fix? Other than that, I do not see any reason why not to merge.

**Comment by adler-j** [comment]
I'm onto this!

**Comment by adler-j** [comment]
Fixed this now, anyone wanna try if performance is improved? For me I found this to be much faster anyway.

**Comment by mehrhardt** [comment]
Works great and about 1.5-2 times faster on my test problem.

**Pull request merged**
