### PR TITLE
REL: add Zenodo badge to README.md, closes #764

### LINKED ISSUE #764: Add an ODL DOI to make the repository cite-able
We can make the repository in itself citeable using [these steps](https://guides.github.com/activities/citable-code/).

Do we want to do this, or are we waiting for the article instead? See #397.

### PR DESCRIPTION
**Pull request by kohr-h**

### CODE REVIEW

**Comment by adler-j** [comment]
* Some names are off: `niinimaki; hilding79`

* The name should not be stuff about release notes, i guess? Can we change that? Also remove odlgroup/odl while at it

* It seems the theory folder under doc is rather big (about 20% of the repo), yet I guess users cant even read it? Can you move it to some personal repo or set up a new repo under odlgroup?

* Licence says "other", while we have a well known licence

* The bibtex export looks like this:
  
  ```
  @misc{jonas_adler_2017_249479,
    author       = {Jonas Adler and
                    Holger Kohr and
                    Axel Ringh and
                    Julian Moosmann and
                    niinimaki and
                    hilding79 and
                    Willem Jan Palenstijn and
                    Chong Chen and
                    Ozan Öktem},
    title        = {{odlgroup/odl: ODL 0.5.3 Release Notes (2017-01-17) 
                     odlgroup/odl: ODL 0.5.3 Release Notes (2017-01-17)}},
    month        = jan,
    year         = 2017,
    doi          = {10.5281/zenodo.249479},
    url          = {https://doi.org/10.5281/zenodo.249479}
  }
  ```
  
  Here the title seems off.

* Also, this partially closes the "odl citation" issue #397

**Comment by kohr-h** [comment]
> Some names are off: niinimaki; hilding79

Can't do anything about it, they're just taken from GH. Not sure if there's a way to manually change that. But the same happens with any new contributor, so people who doesn't expose their real names will be listed with alias.



> The name should not be stuff about release notes, i guess? Can we change that? Also remove odlgroup/odl while at it

Yes, that's a bit annoying. Maybe it can be customized from where it pulls the "main" text.

> It seems the theory folder under doc is rather big (about 20% of the repo), yet I guess users cant even read it? Can you move it to some personal repo or set up a new repo under odlgroup?

Oh dear, that stuff has been lurking around for quite some time now. Should definitely be removed.



> Licence says "other", while we have a well known licence

A Zenodo bug? I'll check.



> The bibtex export looks like this:
> 
> @misc{jonas_adler_2017_249479,
>   author       = {Jonas Adler and
>                   Holger Kohr and
>                   Axel Ringh and
>                   Julian Moosmann and
>                   niinimaki and
>                   hilding79 and
>                   Willem Jan Palenstijn and
>                   Chong Chen and
>                   Ozan Öktem},
>   title        = {{odlgroup/odl: ODL 0.5.3 Release Notes (2017-01-17) 
>                    odlgroup/odl: ODL 0.5.3 Release Notes (2017-01-17)}},
>   month        = jan,
>   year         = 2017,
>   doi          = {10.5281/zenodo.249479},
>   url          = {https://doi.org/10.5281/zenodo.249479}
> }
> 
> Here the title seems off.

Same problem as farther above I guess.



> Also, this partially closes the "odl citation" issue #397

Right, probably completely for now. We'll add a "Citing ODL" or something in `README.md` once we got that goddamn paper out.

**Comment by kohr-h** [comment]
>> Some names are off: niinimaki; hilding79
>> 
> Can't do anything about it, they're just taken from GH. Not sure if there's a way to manually change that. But the same happens with any new contributor, so people who doesn't expose their real names will be listed with alias.

Ozan, you (Jonas) and myself appear as the authors now and the rest as "Other". They're entered in text fields under "Contributors" but from the selections of roles, none really made sense so I chose others.
I didn't bother to change aliases to names since we don't have their consent. Also, I don't know what will happen in the next release. Hopefully there's some kind of intelligent-enough system that tries to keep the changes from before and update what has changed. We'll see.

>> The name should not be stuff about release notes, i guess? Can we change that? Also remove odlgroup/odl while at it
>> 
> Yes, that's a bit annoying. Maybe it can be customized from where it pulls the "main" text.

Now the BibTeX looks like this:
```
@misc{jonas_adler_2017_249479,
  author       = {Jonas Adler and
                  Holger Kohr and
                  Ozan Öktem},
  title        = {Operator Discretization Library (ODL)},
  month        = jan,
  year         = 2017,
  doi          = {10.5281/zenodo.249479},
  url          = {https://doi.org/10.5281/zenodo.249479}
}
```
Better I guess?

I manually pasted the text from the README and changed the formatting a bit so that it looks nicer.

**Comment by adler-j** [comment]
Looks good to me!

**Comment by kohr-h** [comment]
Okay, then I'll merge after CI is finished.

**Comment by kohr-h** [comment]
No idea why no build was triggered in Travis - perhaps this would require enabling "build pushes"? Merging anyway, trivial changes.

**Comment by kohr-h** [comment]
Re-enabled "build pushes", it seems to be the source of the problem.
There's an [open issue on that topic](https://github.com/travis-ci/travis-ci/issues/6612) on the Travis CI issue tracker, and [here's](https://stackoverflow.com/questions/31882306/how-to-configure-travis-ci-to-build-pull-requests-merges-to-master-w-o-redunda) SO discussion on the topic. Leaving it for now, perhaps there's going to be an optimal solution at some point.

**Pull request merged**
