### PR TITLE
MAINT: update numpydoc and rename folder

### PR DESCRIPTION
**Pull request by kohr-h**
This needs a force-push in the submodule first, which will change the commit hash and requires adaption of the pointer here.

### CODE REVIEW

**Comment by adler-j** [comment]
Not quite sure what this does, is it ready?

**Comment by kohr-h** [comment]
> Not quite sure what this does, is it ready?

It basically just advances the submodule pointer. First the submodule needs the update, then the new link goes here, then we can merge.

**Comment by kohr-h** [comment]
Referring to https://github.com/odlgroup/numpydoc/pull/1

I'll do the push on the submodule, adapt this PR and merge it, okay?

**Comment by kohr-h** [comment]
Okay, seems like everything is fine, waiting for the doc build.

**Pull request merged**
