### PR TITLE
Issue 277  show

### PR DESCRIPTION
**Pull request by adler-j**
Some fixes, now works with (at least)

- [x] Windows
  - [x] IPython in spyder
  - [x] Python in spyder
  - [x] Python commandline

Please verify for other platforms and we can finally merge. The following should be tested:

* All tests in examples/visualization.
* Some test using ShowPartial, for example `odl-examples/pde_laplacian.py`.

Ping @kohr-h, @moosmann

### CODE REVIEW

**Comment by moosmann** [comment]
Add `plt.show()` at the end of `odl-examples/pde_laplacian.py`, otherwise the figure window freezes after execution and I have to force quit.

Using spyder with ipython and inline plotting, all examples which use figure updates (`odl-examples/pde_laplacian.py`, `show_update_*d.py`) create an extra inline image in each iteration. Plotting into the same figure doesn't work in `show_1d.py`. Instead of that three single images are created inline. Not using inline plotting, the examples work normally.

Using PyCharm or ipython/python command line, examples with `show=True` (or `plt.show()`) block code execution until the figure window is close unless I'm using `plt.ion()` or `show=False` with `plt.show(block=False)` or Spyder with ipython and inline off.

Except that, all examples in examples/visualization and `odl-examples/pde_laplacian.py` are working on my machine (Ubuntu 14.04) when using

- PyCharm
- python command line
- ipython command line
- Spyder ipyhton inline off

**Comment by adler-j** [comment]
> Add plt.show() at the end of odl-examples/pde_laplacian.py, otherwise the figure window freezes after execution and I have to force quit.

Will do.

> Using spyder with ipython and inline plotting, all examples which use figure updates (odl-examples/pde_laplacian.py, show_update_*d.py) create an extra inline image in each iteration. Plotting into the same figure doesn't work in show_1d.py. Instead of that three single images are created inline. Not using inline plotting, the examples work normally.

Do you mean that a new image is created with the next iterate, or that the old image is updated and an empty new image is created? What three images are shown in the 1d case? How is the 1d case different from the 2d case?

> Using PyCharm or ipython/python command line, examples with show=True (or plt.show()) block code execution until the figure window is close unless I'm using plt.ion() or show=False with plt.show(block=False) or Spyder with ipython and inline off.

This is the expected behaviour of matplotlib, so that will stay.

> Except that, all examples in examples/visualization and odl-examples/pde_laplacian.py are working on my machine (Ubuntu 14.04) when using

> - PyCharm
> - python command line
> - ipython command line
> - Spyder ipyhton inline off
    
Great work, thanks!

**Comment by kohr-h** [comment]
> Using spyder with ipython and inline plotting, all examples which use figure updates (odl-examples/pde_laplacian.py, show_update_*d.py) create an extra inline image in each iteration. Plotting into the same figure doesn't work in show_1d.py. Instead of that three single images are created inline. Not using inline plotting, the examples work normally.

This is the same behavior I pointed out before, see #217. It will help to adapt the examples such that the returned figure is stored somewhere, which suppresses immediate inline plotting (hopefully).

**Comment by kohr-h** [comment]
I'll check this later today, but since I use roughly the same configuration as @moosmann, results won't be too different I guess. I also have the newest versions of spyder (2.3.8) and matplotlib (1.5.1) installed.

**Comment by moosmann** [comment]
> 

    Using spyder with ipython and inline plotting, all examples which use figure updates (odl-examples/pde_laplacian.py, show_update_*d.py) create an extra inline image in each iteration. Plotting into the same figure doesn't work in show_1d.py. Instead of that three single images are created inline. Not using inline plotting, the examples work normally.

Do you mean that a new image is created with the next iterate, or that the old image is updated and an empty new image is created? What three images are shown in the 1d case? How is the 1d case different from the 2d case?

    Using PyCharm or ipython/python command line, examples with show=True (or plt.show()) block code execution until the figure window is close unless I'm using plt.ion() or show=False with plt.show(block=False) or Spyder with ipython and inline off.

This is the expected behaviour of matplotlib, so that will stay.

    Except that, all examples in examples/visualization and odl-examples/pde_laplacian.py are working on my machine (Ubuntu 14.04) when using

        PyCharm
        python command line
        ipython command line
        Spyder ipyhton inline off

Great work, thanks!

**Comment by moosmann** [comment]
Oops. Misclicked. Reopened.

**Comment by adler-j** [comment]
> A new image is created not updated. In the 1d case, three images with a single plot are created. But I think the behavior is also related to which matplotlib version, backends, etc ist used. I just ran the show_1d.py example on Chong's machine in Spyder with inline plotting and it worked properly. In the 2d case the same behavior is observed i.e. in each iterate a new image is created.

I think we will have to live with that, IPython seems to invalidate old fig handles once shown so we cant update them in any sensible manner.

Waiting for @kohr-h to test this then I'll pull.

**Comment by moosmann** [comment]
> I think we will have to live with that, IPython seems to invalidate old fig handles once shown so we cant update them in any sensible manner.

I think so, too. If it doesn't work properly in one case or the other, one still can get it working using proper arguments or pyplot functions. Anyway, very nice functionality.

**Comment by kohr-h** [comment]
Some observations:

- Plotting in native Python console is much faster than in IPython
- When the Laplacian example is done and you close the figure, a new figure is opened with the final result. Only after you close that, the program is done with execution. That doesn't happen with the `show_update_2d` example, so probably the final `plt.show()` command suppresses that.
- I don't have any inline figures during update, that works fine for me.

Nice otherwise.

**Comment by kohr-h** [comment]
I should add that I tested Spyder with both native Python console and IPython.

**Comment by adler-j** [comment]
With what setup do we observe:

> Add plt.show() at the end of odl-examples/pde_laplacian.py, otherwise the figure window freezes after execution and I have to force quit.

**Comment by kohr-h** [comment]
> so probably the final plt.show() command suppresses that.

It does. Maybe that's connected to the freezing issue?

**Comment by moosmann** [comment]
> With what setup do we observe:

> > Add plt.show() at the end of odl-examples/pde_laplacian.py, otherwise the figure window freezes after execution and I have to force quit.

Using PyCharm on Ubuntu. Using python/ipython command line there's no freeze, but without `plt.show()` the window closes as soon as code execution is finished. Using Spyder with python there is no freeze and the window stays open. Using Spyder with ipython and inline plotting there's no freezing (but additional images are created in each loop).

**Pull request merged**
