### PR TITLE
MAINT: remove BOMs

### PR DESCRIPTION
**Pull request by kohr-h**
Trivial PR that removes those annoying BOM unicode characters. Some tools get tripped by them.

(For the modified files, I've also updated the copyright years.)

### CODE REVIEW

**Comment by kohr-h** [comment]
CI failures again due to incompatible Numpy, see #1500

**Comment by adler-j** [comment]
what really changed here? I'm only seeing copyright years and a single other change.

**Comment by kohr-h** [comment]
> what really changed here? I'm only seeing copyright years and a single other change.

The BOM characters are removed. They are invisible and don't show up here. But if you look at the git diff, for instance, you see this:

    -<U+FEFF># Copyright 2014-2017 The ODL contributors
    +# Copyright 2014-2019 The ODL contributors

These marks are only useful in Python 2, and tend to be added by Windows editors. We usually don't need unicode support in source files, and if we do, we make it explicit by some other measure.

**Comment by adler-j** [comment]
All good then, go ahead!

**Pull request merged**
