### PR TITLE
ENH: Change kaczmarz to parallel beam

### PR DESCRIPTION
**Pull request by adler-j**
Fix according to @MatthiasJE

### CODE REVIEW

**Comment by MatthiasJE** [comment]
I recommend to make this example smaller scale or move it to "contrib", e.g. shape=[100, 100], num_angles=160.

In addition, I was thinking that it may be better to make these subset operators a "Broadcasting operator".

Otherwise it works really well.

**Comment by MatthiasJE** [comment]
A positive comment on speed that may be included in the example:

```
ray_trafos = odl.BroadcastOperator(*ray_trafos_list)

import src

x1 = ray_trafos.range.zero()
src.tic()
ray_trafos(phantom, out=x1)
src.toc()

x2 = ray_trafos.range.zero()
src.tic()
for i in range(ray_trafos.size):
    ray_trafos[i](phantom, out=x2[i])
src.toc()

```

> Elapsed time is 0.166328 seconds.
> Elapsed time is 0.167632 seconds.

This is really good!

**Comment by MatthiasJE** [comment]
Here is a negative result about adjointness:

```
A = ray_trafos[0]
X = A.domain
Y = A.range

x = X.one()
y = Y.one()

print(y.inner(A(x)))
print(x.inner(A.adjoint(y)))
print(y.inner(A(x)) - x.inner(A.adjoint(y)))
```

> 249.86969972769987
> 251.32757812500006
> -1.4578783973001919

**Comment by MatthiasJE** [comment]
Ups, this is about #1110.

**Comment by adler-j** [comment]
Regarding the size, even with the current parameters this takes like one second with astra_gpu, making it smaller would basically make it instant and ruins the visualization, but perhaps I can add a pause to the callback instead.

The adjoint-ness is a "well known" problem in that our backends do not have exactly matched adjoints (unless you use `impl='astra-cpu'`).

**Comment by MatthiasJE** [comment]
Sure, but I would prefer if "standard" examples would not require backends like astra and hardware like gpus. In the end, this example is about the functionality of ODL. That being said, it would also be good to have more complicated examples that require certain backends and hardware (and show how to use them).

**Comment by adler-j** [comment]
I agree. I'll try to downscale it and add some artificial pauses to improve the visualization.

**Comment by adler-j** [comment]
Fixed the scaling

**Comment by MatthiasJE** [comment]
But you did not commit this yet, right?

**Comment by MatthiasJE** [comment]
I installed astra with

`conda install -c astra-toolbox astra-toolbox`

and indeed, the scaling issue is gone. So easy :)

**Comment by MatthiasJE** [comment]
If we introduce the BroadcastOperator

`ray_trafo = odl.BroadcastOperator(ray_trafos)`

e.g. in line 51

then we can write line 59 as 

`data = ray_trafo(phantom)`

and line 74 as

`odl.solvers.kaczmarz(ray_trafo, x, data, niter=5, omega=omega, callback=callback, callback_loop='inner')
`
both of which I find more intuitive.

Otherwise, I like the example and it could be merged.

**Comment by adler-j** [comment]
Agree with your comments, I'll do that!

**Comment by adler-j** [comment]
Considering this reviewed. Will merge after CI.

**Pull request merged**
