### PR TITLE
DOC: move documentation from _call to __init__, closes #530

### LINKED ISSUE #530: Move usage examples from _call to __init__
We currently have documentation on how operators behave in the _call method. This is ok for the webpage, but for editors we need this to show up more simply, and there is no reasonable way to find _call as it is right now.

My suggestion is that we move the `_call` examples into `__init__`. This should reduce some code overhead (since we dont need to init things twice) and also make finding this information much easier.

### PR DESCRIPTION
**Pull request by adler-j**
Quite trivial pull, moved doc from _call to __init__. Should have no changes to actual code.

### CODE REVIEW

**Comment by adler-j** [comment]
Minor bugs, will fix and rebase after review.

**Comment by kohr-h** [comment]
Were that all examples in `_call`? Was not that bad after all..
Anyway, fix, rebase and merge.

**Comment by adler-j** [comment]
Basically did a regexpr for `_call` and moved all examples to `__init__`, so these are all.

**Comment by adler-j** [comment]
Merge after CI.

**Pull request merged**
