### PR TITLE
TST: update tests unsupervised foms.

### PR DESCRIPTION
**Pull request by aringh**
Increase dimension of spaces to reduce risk of random test fails.

### CODE REVIEW

**Comment by aringh** [comment]
I didn't seem to take to long on my laptop. My experience was that if we don't increase the sizes, then we need to increase tolerances up to around 0.4 to not get random fails to often. And that kind of tolerance seemed a little bit ridiculous.

I think that the reason for that noone has noticed this (or at least reported it) is that it is in the `contrib` package. In connection to the discussion in #1354, since this will probably only be run manually by anyone how explicitly wants to test if this works as expected, to me it doesn't seem to bad even if the runtime would be as much as a second.

**Comment by adler-j** [comment]
0.19 is *a lot* of time. We have 5000 tests, at that runtime it would take 20 minutes to run them :/

**Comment by aringh** [comment]
I know. But I still claim that if the tests are _never_ run unless one explicitly does `pytest odl/contrib/fom/test/test_unsupervised.py`, those 0.19 seconds is not what takes time. If I do take the time to run these tests, I therefore prefer that they actually do not fail. Of course, we could increase tolerance levels in the test, but as I wrote you need to increase them quite a lot it seems.

Go or no go?

**Comment by adler-j** [comment]
Oh, this is in contrib? I'm a slow thinker at times...

Just go ahead!

**Comment by adler-j** [comment]
Just some closing words: For contrib tests may easily take more time if we need, we should probably even add more tests to this...

**Pull request merged**
