### PR TITLE
TST: Add doctest to RayTransform

### PR DESCRIPTION
**Pull request by adler-j**

### CODE REVIEW

**Comment by adler-j** [comment]
Then why did the test pass?

**Comment by kohr-h** [comment]
Because we have no Travis test scenario for minimal dependencies :-)

**Comment by adler-j** [comment]
Well that is a bit worrying. With that said, don't we ignore certain files in the tests?

**Comment by kohr-h** [comment]
Let me just in a non-smart-ass way recall [this conversation](https://github.com/odlgroup/odl/pull/1164#discussion_r141533959), maybe it wasn't such a bad idea after all.

We don't ignore anything in `tomo`, that would also help, of course.

**Comment by adler-j** [comment]
*whistles* anyway I guess you have quite a point there :/ With that said there are also weird combinations of dependencies that we technically should test as well (ASTRA but not PYFFTW?).

Anyway, would a solution not be to simply ignore tomo depending on the existence of *any* backend?

**Comment by kohr-h** [comment]
> whistles anyway I guess you have quite a point there :/ With that said there are also weird combinations of dependencies that we technically should test as well (ASTRA but not PYFFTW?).

Well, of course, we cannot test *all* scenarios, and maybe not all are independent. But I think one test for the minimal installation scenario would already catch the majority of bugs, which are unfenced imports of optional packages and tests that should be excluded but aren't.



> Anyway, would a solution not be to simply ignore tomo depending on the existence of any backend?

That would make sense. Of course, we can use a finer granularity if we want to (e.g. geometries don't have extra deps), but that seems like too much extra maintenance required.

**Comment by adler-j** [comment]
Since this cannot go in as is, I'll close this and perhaps re-open it at some later point, but that would be some effort in doing it properly.

**Pull request closed without merging**
