### PR TITLE
MAINT: Make several strings case insensitive, see #1454

### PR DESCRIPTION
**Pull request by adler-j**
Further fixes to capitalization of string parameters

### CODE REVIEW

**Comment by kohr-h** [comment]
Looks like you got some PEP8 work to do :-)
The "invalid escape sequence" errors are docstrings that have math but are not raw strings (`r"""`). Easy fix: search-and-replace `\\` with `\` and put an `r` in front of the docstring.

**Comment by adler-j** [comment]
I'm not getting the invalid escape sequence locally, do you have any idea why it started happening now?

**Comment by kohr-h** [comment]
Looks like you used an unrecognized email address for committing. You may want to add it to your account.

**Comment by kohr-h** [comment]
> I'm not getting the invalid escape sequence locally, do you have any idea why it started happening now?

The only thing I can imagine is changes in the `pycodestyle` package that pep8speaks uses. But it's due to something we want to fix anyway.

**Comment by adler-j** [comment]
Ok, monster commit coming through to fix these issues we're having.

**Comment by kohr-h** [comment]
Now that the monster-commit touched a lot of files, can you also do the copyright year update on those?

**Comment by adler-j** [comment]
Will do the copyright. But anyway, how do I get pep8speaks to rerun?

**Comment by adler-j** [comment]
@pep8speaks resume

Maybe this works?

**Comment by adler-j** [comment]
@pep8speaks pep8ify

**Comment by adler-j** [comment]
I have a creeping feeling that @pep8speaks ignores me.

**Comment by kohr-h** [comment]
> Comment last updated on February 13, 2019 at 09:56 Hours UTC

Maybe the issues still exist?

**Comment by kohr-h** [comment]
You can look at the editing history of the comment to see what changed.

**Comment by adler-j** [comment]
Sure, but for some reason it ignored e90cc53 :/

**Comment by adler-j** [comment]
I'll see if I can fix the last stuff as well so that others arn't harassed by these errors, then we can merge this.

**Comment by sbanert** [comment]
At least in `odl/contrib/fom/supervised.py`, @pep8speaks points at things which have not been touched by commits (as far as I see) and therefore still exist. As far as I see, @pep8speaks checks the whole file, once it's touched by any commit in the pull request.

**Comment by adler-j** [comment]
Ok, I frankly went ahead and disabled W504 for now. Personally I don't think it adds to much and it seems that editors etc disable this warning by default.

**Comment by adler-j** [comment]
It seems @pep8speaks is ignoring https://github.com/odlgroup/odl/blob/master/.pep8speaks.yml, or perhaps it uses the one on master. How about we go ahead and merge this and see if that fixes it.

**Comment by adler-j** [comment]
Yeah, it seems it's reading of master, see https://github.com/OrkoHunter/pep8speaks/issues/55. How about we merge this then?

**Comment by kohr-h** [comment]
> Yeah, it seems it's reading of master, see [OrkoHunter/pep8speaks#55](https://github.com/OrkoHunter/pep8speaks/issues/55). How about we merge this then?

That explains! :roll_eyes:

**Comment by adler-j** [comment]
Both W503 and W504 are disabled by default in basically all editors I've seen. I propose we also ignore both since readability wise it truly adds very little and makes PRs somewhat more of a hassle to write.

**Comment by kohr-h** [comment]
Okay fine with me. My personal preference is to break before the operator, after having seen both variants. For future PRs then.

**Pull request merged**
