### PR TITLE
MAINT: update sphinxext submodule, closes #845

### LINKED ISSUE #845: Update numpydoc submodule
The upstream repo has advanced a bit since we branched off. Doesn't look like too much has happened, but one thing they added is a section duplication check that caught an error in #841.
```
reading sources... [  7%] generated/odl.discr.grid.uniform_sampling_fromintv                         
Exception occurred:
  File "/home/hkohr/git/odl/doc/sphinxext/numpydoc/docscrape.py", line 336, in _parse
    raise ValueError(msg)
ValueError: The section See Also appears twice in the docstring.
```
This is nice, and we should rebase on the current master.

### PR DESCRIPTION
**Pull request by kohr-h**

### CODE REVIEW

**Comment by adler-j** [comment]
I don't see any update performed to [odlgroup/numpydoc](https://github.com/odlgroup/numpydoc), can that be correct? Or has the bugs we fixed locally been fixed upstream?

**Comment by kohr-h** [comment]
Well yeah, I rebased and force-pushed to master directly. But we still have [the fixes](https://github.com/numpy/numpydoc/compare/master...odlgroup:master) as before, just off a more recent point.

**Comment by kohr-h** [comment]
So this PR only changes the submodule pointer to the new HEAD.

**Comment by kohr-h** [comment]
Builds fine with the last fix, and submodule pointer is correct. Will merge after CI.

**Pull request merged**
