### PR TITLE
BUG: Handle list of length one appropriately for SamplingOperator.adj…

### LINKED ISSUE #1350: Adjoint of SamplingOperator error in 1D
The adjoint of the SamplingOperator is not working for me. 

ODL version.
'0.6.1.dev0'

Minimal example
````
import numpy as np
import odl

U = odl.uniform_discr(0, 100, 100) 
u = U.one()

idx = [2,3,4]

E = odl.SamplingOperator(U,idx)

E.adjoint(E(u))
```

### PR DESCRIPTION
**Pull request by adler-j**
…oint, closes #1350

### CODE REVIEW

**Comment by kohr-h** [comment]
A test that checks the reported bug code would be nice.

**Comment by adler-j** [comment]
I guess I can get some time off to add tests for this class, but it's quite an effort. Perhaps just merge this and I'll make an issue about it. That way our user can get the fix asap.

**Comment by kohr-h** [comment]
But I guess this one test case would be pretty simple, no? That would at least ensure that we don't resurrect the bug when changing the code again.

**Comment by adler-j** [comment]
I guess I could, but this class has no real tests at all (its all doctests)

**Comment by kohr-h** [comment]
I know, what's wrong with just adding one test function for only this to the `tensor_ops_tests.py` (I guess)? That also makes pretty obvious that there are tests missing :-)

**Comment by adler-j** [comment]
So I added the requested test now, all OK?

**Comment by kohr-h** [comment]
> So I added the requested test now, all OK?

Way more than I expected, but all the better.

**Pull request merged**
