### PR TITLE
Pybind11

### PR DESCRIPTION
**Pull request by kohr-h**
Pushed to a new branch by mistake - never mind. This seems to work according to tests on my machine and on our Jenkins. Can you test it on Windows @adler-j? If that goes through, I suggest we [merge in odlpp](https://github.com/odlgroup/odlpp/pull/13) to master, update the submodule and merge here.

### CODE REVIEW

**Comment by adler-j** [comment]
May need to revert this, did you verify it builds with MSVC and Clang?

**Comment by adler-j** [comment]
Well I be damned, missed the branch switcharoo, will check today, but please try Clang.

**Comment by kohr-h** [comment]
> with MSVC

How am I supposed to do that?



> Clang

I'll try it

**Comment by adler-j** [comment]
> How am I supposed to do that?

Could run a virtual machine I suppose.

I thought it was merged since you closed, but it was the other one that was closed, got me confused.

**Comment by kohr-h** [comment]
I didn't actively close anything, maybe something like that happened when I deleted the other branch? Sorry about the confusion.

I don't have a win installation lying around. We should activate our the Jenkins on the windows machine again...

Now installing CUDA 7.5, seems to have hit the repos recently. My old 7.0 doesn't support Clang.

**Comment by kohr-h** [comment]
Works with clang. A build job for odlpp with clang wouldn't hurt I guess.

**Comment by adler-j** [comment]
This will have to wait, it seems pybind11 has introduced heaps of bugs for VS2013, I tried fixing some but more popped up, and apparently the maintainer has no plans to support "only parts of" C++11 (which I can understand). This would have been fine if Nvidia had released VS2015 support for CUDA, but it is currently only part of a "release candidate" that you can access as a "registered developer" (which I am, but I doubt most of our users are). 

Status:
https://developer.nvidia.com/nsight-visual-studio-edition-5_0-new-features

I'll have a look and see if it builds under VS2015 anyway.

**Comment by kohr-h** [comment]
Well okay. Not great but understandable. When will this piece of crap 
appear?

On 02/09/2016 09:07 AM, Jonas Adler wrote:
> This will have to wait, it seems pybind11 has introduced heaps of bugs
> for VS2013, I tried fixing some but more popped up, and apparently the
> maintainer has no plans to support "only parts of" C++11 (which I can
> understand). This would have been fine if Nvidia had released VS2015
> support for CUDA, but it is currently only part of a "release candidate"
> that you can access as a "registered developer" (which I am, but I doubt
> most of our users are).
>
> Status:
> https://developer.nvidia.com/nsight-visual-studio-edition-5_0-new-features
>
> I'll have a look and see if it builds under VS2015 anyway.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/odlgroup/odl/pull/264#issuecomment-181753588>.
>

-- 
Dr Holger Kohr
KTH - Royal Institute of Technology
Dpt of Mathematics
100 44 Stockholm
Tel +46 8 790-6652
Mobil +46 72 0119332

**Comment by adler-j** [comment]
Closing this since #336 will override most of this anyway.

**Pull request closed without merging**
