### PR TITLE
Phase contrast

### PR DESCRIPTION
**Pull request by rajmund**

### CODE REVIEW

**Comment by adler-j** [comment]
What happened here?

**Comment by ozanoktem** [comment]
> What happened here?

Someone worked on a phase contrast example :-) @adler-j , FYI @rajmund is at MaxLab IV.

**Comment by adler-j** [comment]
Well I'd be glad if we managed to get proper phase contrast support in, I was simply sad that it got closed so quickly.

**Comment by rajmund** [comment]
Hi Jonas, 
It was my mistake, I did not mean to do a pull request. I am starting to look into the phase contrast branch, but have not done any modifications.
Rajmund

~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~
Rajmund Mokso
Imaging group head, MedMax project leader
Max IV Laboratory
Lund University
P.O. Box 118, SE-221 00 Lund, Sweden
Visiting address: Fotongatan 2, 225 94 Lund
____________________________
Mobile.: +46-(0)72-551 7497
rajmund.mokso@maxiv.lu.se
www.maxlab.lu.se
~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by rajmund** [comment]
I hope I can manage to contribute in this soon. Will work in it from now time to time.
Rajmund

~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~
Rajmund Mokso
Imaging group head, MedMax project leader
Max IV Laboratory
Lund University
P.O. Box 118, SE-221 00 Lund, Sweden
Visiting address: Fotongatan 2, 225 94 Lund
____________________________
Mobile.: +46-(0)72-551 7497
rajmund.mokso@maxiv.lu.se
www.maxlab.lu.se
~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by adler-j** [comment]
> Hi Jonas,
It was my mistake, I did not mean to do a pull request. I am starting to look into the phase contrast branch, but have not done any modifications.

No problem.

> I hope I can manage to contribute in this soon. Will work in it from now time to time.

That would be excellent! Have fun and ask if there is anything we can help with.

**Pull request closed without merging**
