### PR TITLE
BUG: avoid zero division in ellipse phantom for shape=1 axes

### LINKED ISSUE #776: Ellipse phantoms don't work in "degenerate" spaces
Due to [division by zero](https://github.com/odlgroup/odl/blob/master/odl/phantom/geometric.py#L434-L435), ellipse phantoms don't work if the space has shape of, e.g., `(300, 300, 1)`.

### PR DESCRIPTION
**Pull request by kohr-h**
Closes #776

### CODE REVIEW

**Comment by kohr-h** [comment]
Comments added, okay?

**Comment by adler-j** [comment]
Damn thats an essay :D anyway fine with me

**Comment by kohr-h** [comment]
> Damn thats an essay :D anyway fine with me

Yes, when I started writing the comment I realized that this was more of a special case than I had realized before, since usually we "squeeze" the phantom into the available space, while here we only get a partial phantom. Would you think this should be mentioned in the doc?

**Comment by kohr-h** [comment]
Just went ahead and added a sentence in the docs where it fits. Merge after CI.

**Pull request merged**
