### PR TITLE
Issue 69  auto doc

### PR DESCRIPTION
**Pull request by adler-j**
Initializing a pull request for this, but it is not done yet.

Now only has a few warnings left.

### CODE REVIEW

**Comment by adler-j** [comment]
This branch also contains the fixes of #69, #70 and #71. A huge improvement is that we now will be able to document using 

    `target` 

instead of 

    :class:`odl.my.lib.target`

**Comment by adler-j** [comment]
I actually recommend merge of this now.

**Comment by kohr-h** [comment]
First of all, this is really good stuff. I like the auto-generation of the doc files and the fact that you don't need to add `:class:` everywhere.

Speaking of which, what is different now in the way one documents stuff? The answer to that, plus some general guide, should be added to our documentation.

**Comment by adler-j** [comment]
It is already added in [document.rst](https://github.com/odlgroup/odl/blob/issue-69__auto_doc/doc/source/dev/document.rst).

**Comment by kohr-h** [comment]
I fixed some bad LaTeX style causing warnings in the `pspace_ops` module and added / fixed some stuff in the "How to document" thing. Looks good (except the complaint by Coveralls).

**Pull request merged**
