### PR TITLE
Pybind11

### PR DESCRIPTION
**Pull request by adler-j**
Example of how pybind 11 would work. Most changes are in the odlpp library (also has a branch). Removed test for case that shouldnt fail (`test_getslice_index_error`).

The main issue with pybind11 that i see is that the developer intends to support VS2015 and up, but we need VS2013 support for now, at least until CUDA works with VS2015. Currently this works, but I'll see if we can get VS2013 support into pybind before we proceeed.

### CODE REVIEW

**Comment by adler-j** [comment]
Merge?

**Comment by kohr-h** [comment]
I'm currently building. Just a note: if you don't use the word "issue" in your branch name, Jenkins won't test it. So if there is no open issue number you can use, just name it `issue__<name>` or something. Since this would have been a very good case where an automatic build would have been useful.

**Comment by kohr-h** [comment]
I'm getting errors in the `odlpp` tests:

```
test/cuda_test.py:6: in <module>
    import odlpp.odlpp_cuda as cuda
odlpp/__init__.py:20: in <module>
    from . import odlpp_cuda
E   ImportError: cannot import name 'odlpp_cuda'
__________________________________ ERROR collecting test/cuda_test.py __________________________________
test/cuda_test.py:6: in <module>
    import odlpp.odlpp_cuda as cuda
odlpp/__init__.py:20: in <module>
    from . import odlpp_cuda
E   ImportError: cannot import name 'odlpp_cuda'
```

I'll check my build environment and make a fresh build.

**Comment by kohr-h** [comment]
Didn't update the submodule, oops.

**Comment by kohr-h** [comment]
Now it's segfaulting. Any idea why?

I ran `py.test odlpp/test` through valgrind, here's the output if that helps:

```
collecting 0 items==136063== Invalid read of size 8
==136063==    at 0x4EDA7FB: PyModule_GetDef (in /usr/lib64/libpython3.4m.so.1.0)
==136063==    by 0x4F63481: _PyImport_LoadDynamicModule (in /usr/lib64/libpython3.4m.so.1.0)
==136063==    by 0x4F605C4: ??? (in /usr/lib64/libpython3.4m.so.1.0)
==136063==    by 0x4F4F3F0: PyEval_EvalFrameEx (in /usr/lib64/libpython3.4m.so.1.0)
==136063==    by 0x4F4FDE5: PyEval_EvalCodeEx (in /usr/lib64/libpython3.4m.so.1.0)
==136063==    by 0x4F4CB88: PyEval_EvalFrameEx (in /usr/lib64/libpython3.4m.so.1.0)
==136063==    by 0x4F4FDE5: PyEval_EvalCodeEx (in /usr/lib64/libpython3.4m.so.1.0)
==136063==    by 0x4EC06E4: ??? (in /usr/lib64/libpython3.4m.so.1.0)
==136063==    by 0x4E97F30: PyObject_Call (in /usr/lib64/libpython3.4m.so.1.0)
==136063==    by 0x4F4AA9E: PyEval_EvalFrameEx (in /usr/lib64/libpython3.4m.so.1.0)
==136063==    by 0x4F4FDE5: PyEval_EvalCodeEx (in /usr/lib64/libpython3.4m.so.1.0)
==136063==    by 0x4F4CB88: PyEval_EvalFrameEx (in /usr/lib64/libpython3.4m.so.1.0)
==136063==  Address 0x9 is not stack'd, malloc'd or (recently) free'd
==136063== 
==136063== 
==136063== Process terminating with default action of signal 11 (SIGSEGV)
==136063==  Access not within mapped region at address 0x9
==136063==    at 0x4EDA7FB: PyModule_GetDef (in /usr/lib64/libpython3.4m.so.1.0)
==136063==    by 0x4F63481: _PyImport_LoadDynamicModule (in /usr/lib64/libpython3.4m.so.1.0)
==136063==    by 0x4F605C4: ??? (in /usr/lib64/libpython3.4m.so.1.0)
==136063==    by 0x4F4F3F0: PyEval_EvalFrameEx (in /usr/lib64/libpython3.4m.so.1.0)
==136063==    by 0x4F4FDE5: PyEval_EvalCodeEx (in /usr/lib64/libpython3.4m.so.1.0)
==136063==    by 0x4F4CB88: PyEval_EvalFrameEx (in /usr/lib64/libpython3.4m.so.1.0)
==136063==    by 0x4F4FDE5: PyEval_EvalCodeEx (in /usr/lib64/libpython3.4m.so.1.0)
==136063==    by 0x4EC06E4: ??? (in /usr/lib64/libpython3.4m.so.1.0)
==136063==    by 0x4E97F30: PyObject_Call (in /usr/lib64/libpython3.4m.so.1.0)
==136063==    by 0x4F4AA9E: PyEval_EvalFrameEx (in /usr/lib64/libpython3.4m.so.1.0)
==136063==    by 0x4F4FDE5: PyEval_EvalCodeEx (in /usr/lib64/libpython3.4m.so.1.0)
==136063==    by 0x4F4CB88: PyEval_EvalFrameEx (in /usr/lib64/libpython3.4m.so.1.0)
```

**Comment by adler-j** [comment]
I had that once as well, never came back. Make sure you have a perfectly clear build (remove odlpp from site-packages as well).

**Comment by adler-j** [comment]
btw we want this to build smoothly before we pull, a few tries on some computers wont hurt.

**Comment by kohr-h** [comment]
I'll run it again. Just pushed a little fix for an include bug that your MS compiler just swallowed I guess.

**Comment by kohr-h** [comment]
Sure, we can go around the office tomorrow.

**Comment by kohr-h** [comment]
I got it to work on Python 2, but it still segfaults on Python 3.

**Comment by kohr-h** [comment]
```
python -c "import odlpp"
Segmentation fault (core dumped)
```

I think there is something wrong with the import logic in pybind11.

**Comment by adler-j** [comment]
Any chance you can look into it? I aint got python3 on any easily accessible machine.

**Comment by adler-j** [comment]
How about the `_import_array` thing we do, maybe we can remove it.

**Comment by kohr-h** [comment]
I'll try to find the source. Possibly `_import_array`. I've no idea if it's needed any longer.

**Comment by kohr-h** [comment]
Apparently it's no longer needed, but it didn't solve the issue either.

**Comment by adler-j** [comment]
Could be a python3 issue with pybind11, check what version he uses on the build server.

**Comment by kohr-h** [comment]
More weird stuff going on: In Python 2, obviously not everything is fine, it just crashes later.

When I run the `cu_ntuples.py` tests, it crashes in between, consistently in the `test_vector_norm[ p = 3.0 ]` test case, to be precise. The same for the `discr_ops_test.py::test_discr_part_deriv_cuda` case which consistently fails. All the other CUDA related tests run, but I'm not sure how much of that is actually reproducible.

I'll do some tests on my laptop later.

**Comment by kohr-h** [comment]
> Could be a python3 issue with pybind11, check what version he uses on the build server.

Our submodule `HEAD` is two commits behind, and those were only text, not code.

**Comment by adler-j** [comment]
I was referring to the version of python that he uses on the build server (2.7, 3.5) etc. But if python 2 fails, that aint it. We need to do some valgrind on this.

**Comment by adler-j** [comment]
Maybe it is because we are missing [this line](https://github.com/wjakob/pybind11/blob/4b279327a3d416687d6558e4b6fef8ee5486a710/example/example.cpp#L41) that should be [here](https://github.com/odlgroup/odlpp/blob/f4fbfa2ed5a272264249f2770dfc57c923ffd6d0/odlpp/cuda/cuda.cpp#L205)?

**Comment by adler-j** [comment]
Quite sure that is it, I even get this nice warning from MSVC (this is why you make sure your builds are warning free, perhaps we should go full warnings as errors).

> d:\github\odl\odlpp\odlpp\cuda\cuda.cpp(205): warning C4715: 'initodlpp_cuda' : not all control paths return a value

**Comment by adler-j** [comment]
Pushed [a commit](https://github.com/odlgroup/odlpp/commit/8932c81e25a538ff262c38b8bd69a5e18741b407) that should fix this.

**Comment by kohr-h** [comment]
Jenkins builds both work. I'll test it on my machine, too.

**Comment by kohr-h** [comment]
On my laptop it still segfaults, now at the very beginning though for 2.7. But I'll give it another shot soon and really clean up properly before I build.

**Comment by kohr-h** [comment]
What is really odd is that the CUDA examples like convolution test and speed test run without problems. Just tried that code out of curiosity.

**Comment by adler-j** [comment]
Same thing for me, I guess some thinking is needed here. I think we screw up reference counting at some point (perhaps pybind11 has a different convention).

**Comment by adler-j** [comment]
I now solved it on my linux machine, it seems there was a bug in pybind11, i submitted [a pull request](https://github.com/wjakob/pybind11/pull/45), lets hope it gets accepted.

**Comment by kohr-h** [comment]
At least the error (message) propagation is *way* better:
```
MemoryError: std::bad_alloc: no CUDA-capable device is detected
```
Need to retry after restart. There is some bug in the Linux driver which breaks CUDA after sleep / hibernate.

**Comment by adler-j** [comment]
Holy f that is indeed better.

**Comment by kohr-h** [comment]
Getting the following error:
```
cuda_test.py ....*** Error in `/home/hkohr/.virtualenvs/odl-py3.4/bin/python3.4': double free or corruption (fasttop): 0x0000000003374630 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x77a17)[0x7f3dc6e1ba17]
/lib64/libc.so.6(+0x7d897)[0x7f3dc6e21897]
/lib64/libc.so.6(+0x7e0fb)[0x7f3dc6e220fb]
/home/hkohr/.virtualenvs/odl-py3.4/lib64/python3.4/site-packages/odlpp/odlpp_cuda.so(_ZN8pybind116bufferD1Ev+0x59)[0x7f3dc04499b1]
/home/hkohr/.virtualenvs/odl-py3.4/lib64/python3.4/site-packages/odlpp/odlpp_cuda.so(_ZN8pybind115arrayD1Ev+0x38)[0x7f3dc044e894]
/home/hkohr/.virtualenvs/odl-py3.4/lib64/python3.4/site-packages/odlpp/odlpp_cuda.so(_ZZN8pybind1112cpp_functionC4INS_5arrayEIR14CudaVectorImplIfENS_5sliceEEINS_4nameENS_7siblingENS_9is_methodEEEEPFT_DpT0_EDpOT1_ENKUlPNS0_14function_entryEP7_objectSL_SL_E_clESJ_SL_SL_SL_+0xe3)[0x7f3dc04ca0bd]
/home/hkohr/.virtualenvs/odl-py3.4/lib64/python3.4/site-packages/odlpp/odlpp_cuda.so(_ZZN8pybind1112cpp_functionC4INS_5arrayEJR14CudaVectorImplIfENS_5sliceEEJNS_4nameENS_7siblingENS_9is_methodEEEEPFT_DpT0_EDpOT1_ENUlPNS0_14function_entryEP7_objectSL_SL_E_4_FUNESJ_SL_SL_SL_+0x58)[0x7f3dc04ca374]
/home/hkohr/.virtualenvs/odl-py3.4/lib64/python3.4/site-packages/odlpp/odlpp_cuda.so(_ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_+0x1b1)[0x7f3dc044beb2]
/usr/lib64/libpython3.4.so.1.0(PyEval_EvalFrameEx+0x66dd)[0x7f3dc7487b9d]
/usr/lib64/libpython3.4.so.1.0(PyEval_EvalCodeEx+0x85e)[0x7f3dc748997e]
/usr/lib64/libpython3.4.so.1.0(+0x8ca83)[0x7f3dc73fda83]
/usr/lib64/libpython3.4.so.1.0(PyObject_Call+0x68)[0x7f3dc73d5f28]
/usr/lib64/libpython3.4.so.1.0(PyEval_EvalFrameEx+0xdca)[0x7f3dc748228a]
/usr/lib64/libpython3.4.so.1.0(PyEval_EvalCodeEx+0x85e)[0x7f3dc748997e]
/usr/lib64/libpython3.4.so.1.0(+0x8c9a6)[0x7f3dc73fd9a6]
/usr/lib64/libpython3.4.so.1.0(PyObject_Call+0x68)[0x7f3dc73d5f28]
/usr/lib64/libpython3.4.so.1.0(PyEval_EvalFrameEx+0xdca)[0x7f3dc748228a]
/usr/lib64/libpython3.4.so.1.0(PyEval_EvalCodeEx+0x85e)[0x7f3dc748997e]
/usr/lib64/libpython3.4.so.1.0(PyEval_EvalFrameEx+0x5904)[0x7f3dc7486dc4]
/usr/lib64/libpython3.4.so.1.0(PyEval_EvalCodeEx+0x85e)[0x7f3dc748997e]
/usr/lib64/libpython3.4.so.1.0(PyEval_EvalFrameEx+0x5904)[0x7f3dc7486dc4]
/usr/lib64/libpython3.4.so.1.0(PyEval_EvalFrameEx+0x7820)[0x7f3dc7488ce0]
/usr/lib64/libpython3.4.so.1.0(PyEval_EvalCodeEx+0x85e)[0x7f3dc748997e]
/usr/lib64/libpython3.4.so.1.0(+0x8ca83)[0x7f3dc73fda83]
/usr/lib64/libpython3.4.so.1.0(PyObject_Call+0x68)[0x7f3dc73d5f28]
/usr/lib64/libpython3.4.so.1.0(+0x7917d)[0x7f3dc73ea17d]
/usr/lib64/libpython3.4.so.1.0(PyObject_Call+0x68)[0x7f3dc73d5f28]
/usr/lib64/libpython3.4.so.1.0(+0xbae20)[0x7f3dc742be20]
/usr/lib64/libpython3.4.so.1.0(PyObject_Call+0x68)[0x7f3dc73d5f28]
/usr/lib64/libpython3.4.so.1.0(PyEval_EvalFrameEx+0x2296)[0x7f3dc7483756]
/usr/lib64/libpython3.4.so.1.0(PyEval_EvalFrameEx+0x7820)[0x7f3dc7488ce0]
/usr/lib64/libpython3.4.so.1.0(PyEval_EvalCodeEx+0x85e)[0x7f3dc748997e]
/usr/lib64/libpython3.4.so.1.0(+0x8c9a6)[0x7f3dc73fd9a6]
/usr/lib64/libpython3.4.so.1.0(PyObject_Call+0x68)[0x7f3dc73d5f28]
/usr/lib64/libpython3.4.so.1.0(PyEval_EvalFrameEx+0xdca)[0x7f3dc748228a]
/usr/lib64/libpython3.4.so.1.0(PyEval_EvalCodeEx+0x85e)[0x7f3dc748997e]
/usr/lib64/libpython3.4.so.1.0(PyEval_EvalFrameEx+0x5904)[0x7f3dc7486dc4]
/usr/lib64/libpython3.4.so.1.0(PyEval_EvalCodeEx+0x85e)[0x7f3dc748997e]
/usr/lib64/libpython3.4.so.1.0(+0x8c9a6)[0x7f3dc73fd9a6]
/usr/lib64/libpython3.4.so.1.0(PyObject_Call+0x68)[0x7f3dc73d5f28]
/usr/lib64/libpython3.4.so.1.0(+0x7917d)[0x7f3dc73ea17d]
/usr/lib64/libpython3.4.so.1.0(PyObject_Call+0x68)[0x7f3dc73d5f28]
/usr/lib64/libpython3.4.so.1.0(+0xbaaf0)[0x7f3dc742baf0]
/usr/lib64/libpython3.4.so.1.0(+0xb86c6)[0x7f3dc74296c6]
/usr/lib64/libpython3.4.so.1.0(PyObject_Call+0x68)[0x7f3dc73d5f28]
/usr/lib64/libpython3.4.so.1.0(PyEval_EvalFrameEx+0x2296)[0x7f3dc7483756]
/usr/lib64/libpython3.4.so.1.0(PyEval_EvalFrameEx+0x7820)[0x7f3dc7488ce0]
/usr/lib64/libpython3.4.so.1.0(PyEval_EvalCodeEx+0x85e)[0x7f3dc748997e]
/usr/lib64/libpython3.4.so.1.0(PyEval_EvalFrameEx+0x5904)[0x7f3dc7486dc4]
/usr/lib64/libpython3.4.so.1.0(PyEval_EvalCodeEx+0x85e)[0x7f3dc748997e]
/usr/lib64/libpython3.4.so.1.0(PyEval_EvalFrameEx+0x5904)[0x7f3dc7486dc4]
/usr/lib64/libpython3.4.so.1.0(PyEval_EvalFrameEx+0x7820)[0x7f3dc7488ce0]
/usr/lib64/libpython3.4.so.1.0(PyEval_EvalCodeEx+0x85e)[0x7f3dc748997e]
/usr/lib64/libpython3.4.so.1.0(+0x8ca83)[0x7f3dc73fda83]
/usr/lib64/libpython3.4.so.1.0(PyObject_Call+0x68)[0x7f3dc73d5f28]
/usr/lib64/libpython3.4.so.1.0(+0x7917d)[0x7f3dc73ea17d]
/usr/lib64/libpython3.4.so.1.0(PyObject_Call+0x68)[0x7f3dc73d5f28]
/usr/lib64/libpython3.4.so.1.0(+0xbae20)[0x7f3dc742be20]
/usr/lib64/libpython3.4.so.1.0(PyObject_Call+0x68)[0x7f3dc73d5f28]
/usr/lib64/libpython3.4.so.1.0(PyEval_EvalFrameEx+0xdca)[0x7f3dc748228a]
/usr/lib64/libpython3.4.so.1.0(PyEval_EvalCodeEx+0x85e)[0x7f3dc748997e]
/usr/lib64/libpython3.4.so.1.0(PyEval_EvalFrameEx+0x5904)[0x7f3dc7486dc4]
/usr/lib64/libpython3.4.so.1.0(PyEval_EvalCodeEx+0x85e)[0x7f3dc748997e]
======= Memory map: ========
...
```
Deleted all old installations before and cleaned build environment. I'll check if all references to submodules are correct.

**Comment by adler-j** [comment]
Is this with the fix to pybind11 that I submitted?

**Comment by kohr-h** [comment]
That depends. If the submodule pointer was updated, yes. Otherwise not.

**Comment by kohr-h** [comment]
Where is the fix you submitted? If I update the odlpp issue branch to latest, the pointer into pybind11 is still at [an old state](https://github.com/wjakob/pybind11/tree/6621c17f1037b2bf8e159b287d88fbbd0dcf5ea8) without the fix.

I guess you are referring to your fork. Can you adapt the `.gitmodules` so people (in this case me) don't have to guess how to piece together the working version?

**Comment by adler-j** [comment]
It's available in my private pybind11 fork:

> I now solved it on my linux machine, it seems there was a bug in pybind11, i submitted [a pull request](https://github.com/wjakob/pybind11/pull/45), lets hope it gets accepted.

**Comment by kohr-h** [comment]
> It's available in my private pybind11 fork:

That's what I guessed, too. Would be good, however, if the branch would have a submodule pointer to the commit in that repo instead of the original one where the issue is still present.

**Comment by kohr-h** [comment]
ODL tests now all succeed for 2.7. Building for 3.4 now. Jenkins also seems to be happy (although he runs only the odlpp tests).

**Comment by kohr-h** [comment]
3.4 :+1: 
Should be pretty mergeable then. Will you wait for the upstream fix (based on your PR) so we don't have to refer to your fork?

**Comment by adler-j** [comment]
> Should be pretty mergeable then. Will you wait for the upstream fix (based on your PR) so we don't have to refer to your fork?

Yeah i'll do that.

**Pull request closed without merging**
