### PR TITLE
 stir backend

### PR DESCRIPTION
**Pull request by NikEfth**
Work in progress

### CODE REVIEW

**Comment by adler-j** [comment]
What is the progress on this, should we start reviewing?

**Comment by kohr-h** [comment]
What shall we do with this? Any idea? @ozanoktem?

**Comment by ozanoktem** [comment]
> What shall we do with this? Any idea? @ozanoktem?

We will have to re-start this, I guess when Barbara gets more into the game. Most of the motion stuff will involve STIR and EMrecon.

**Comment by adler-j** [comment]
Closing this since @olivierverdier will re-do this on a separate branch.

**Comment by olivierverdier** [comment]
The work in progress is now on the ("private" branch, don't clone yet!) [olivierverdier/odl/tree/stir](https://github.com/olivierverdier/odl/tree/stir)

**Pull request closed without merging**
